api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # formats:
    #     json: ["application/json"]
    patch_formats:
        mime_types: ['application/ld+json']
        json: ['application/merge-patch+json'] 
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 3
    
   